# This file is a template for a GitLab CI/CD pipeline.
# Uncomment and edit it to fit your needs.
# You can read more about GitLab CI/CD on https://docs.gitlab.com/ee/ci/README.html

# Define stages for the pipeline
stages:
  - build
  - test
  - deploy

# Define variables
variables:
  DJANGO_SETTINGS_MODULE: "GitMD.settings"

# Define jobs for each stage
build:
  stage: build
  image: node:latest
  script:
    - cd src/WebApp/GitMD/frontend
    - npm install
    - npm install remark-gfm
    - npm run build

django_migrate:
  stage: build
  image: python:latest
  script:
    - cd src/WebApp/GitMD
    - python manage.py makemigrations --check --noinput
    - python manage.py migrate

django_test:
  stage: test
  image: node:latest
  script:
    - cd src/WebApp/GitMD
    - python manage.py test

react_test:
  stage: test
  image: python:latest
  script:
    - cd src/WebApp/GitMD/frontend
    - npm test

deploy:
  stage: deploy
  script:
    - echo "Deploying your application here..."
