stages:
  - test

variables:
  DJANGO_SETTINGS_MODULE: "GitMD.settings"

django_test:
  stage: test
  image: python:latest
  before_script:
    - pip install django djangorestframework django-cors-headers pyjwt requests
  script:
    - cd src/WebApp/GitMD
    - python manage.py makemigrations -v 3
    - python manage.py migrate -v 3
    - python manage.py test

react_test:
  stage: test
  image: node:latest
  script:
    - cd src/WebApp/GitMD/frontend
    - npm install
    - npm install remark-gfm
    - npm test
