# Generated by Django 4.2.5 on 2023-12-31 16:13

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdownfile',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='markdownfile',
            name='code',
            field=models.CharField(default=api.models.generate_code, max_length=8, unique=True),
        ),
    ]
