# Generated by Django 4.2.5 on 2023-12-31 17:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_markdownfile_user_alter_markdownfile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdownfile',
            name='code',
            field=models.CharField(default=api.models.generate_code, max_length=8),
        ),
    ]
