# Generated by Django 4.2.5 on 2024-01-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_markdownfile_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markdownfile',
            name='user',
        ),
    ]
