stages:
  -test

.standard-rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'


django-test:
  stage: test
  extends: .standard-rules
  only:
  - master
  - staging
  - MobileAppDev
  - WebAppDev
  image: python:3.11
  before_script:
    - python -m pip install django djangorestframework
    - cd src/WebApp/GitMD
    - echo "Starting server..."
    - Start-Process python -ArgumentList "manage.py runserver" -NoNewWindow
    - sleep 20
  script:
    - echo "Server started. Init test..."
    - python manage.py test
    - echo "Test finished."
    - $process = Get-Process -Id (Get-NetTCPConnection -LocalPort 8000).OwningProcess
    - Stop-Process -ID $process.Id -Force
    - echo "Server stopped."
